### ISSUE TITLE
Please do not name headings as its default name

### ISSUE THREAD

**Issue by Marufjon94f** [Iuterian99/2nd-Exam#5]
https://github.com/Iuterian99/2nd-Exam/blob/c72c07019f0e35cd94ce0598d731e4edb629a46d/index.html#L82

**Comment by Marufjon94f** [comment]
class name should be changed

**Comment by Iuterian99** [comment]
thanks for comment

**Comment by Marufjon94f** [comment]
no problem

**Comment by Iuterian99** [comment]
Done
